#!/bin/sh
#
# Check whether the machine we're running in is the one holding the Elastic IP.
# This actually is not used by ec2-spotter, but is provided for troubleshooting. 
#

cd `dirname $0`
. ./$(hostname -s).conf || exit 1

PATH=/usr/local/bin/:$PATH

TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

self=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)

alloc=$(aws ec2 describe-addresses --allocation-ids $ec2spotter_elastic_ip | jq -r '.Addresses[0].InstanceId')

if [ $self = $alloc ]
then
  echo $self is primary for $ec2spotter_elastic_ip
  exit 0
else
  echo $self is NOT PRIMARY for $ec2spotter_elastic_ip
  exit 1
fi

